classes: ['Car', 'Pedestrian']
data:
  batch_size: 1
  num_workers: 4
  rgb_shape: [288, 1280, 3]
  train_dataset: "KittiStereoDataset"
  val_dataset: "KittiStereoDataset"
  test_dataset: "KittiStereoTestDataset"

  augmentation:
    rgb_mean: [0.485, 0.456, 0.406]
    rgb_std: [0.229, 0.224, 0.225]
    train:
      - ConvertToFloat:
      - PhotometricDistort:
          distort_prob: 1.0
          contrast_lower: 0.5
          contrast_upper: 1.5
          saturation_lower: 0.5
          saturation_upper: 1.5
          hue_delta: 18.0
          brightness_delta: 32
      - CropTop:
          crop_top_index: 100
      - Resize:
          size: [288, 1280]
      - RandomMirror:
          mirror_prob: 0.5
      - Normalize:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
    
    test:
      - ConvertToFloat:
      - CropTop:
          crop_top_index: 100
      - Resize:
          size: [288, 1280]
      - Normalize:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]

path:
  log_path: logs
  checkpoint_path: checkpoints
  preprocessed_path: preprocessed_output

detector:
  classes: ['Car', 'Pedestrian']
  name: Stereo3D

  backbone:
    depth: 34
    pretrained: true
    frozen_stages: -1
    num_stages: 3
    out_indices: [0, 1, 2]
    norm_eval: true
    dilations: [1, 1, 1]

  head:
    num_regression_loss_terms: 13
    num_classes: 2
    preprocessed_path: preprocessed_output

    anchors_cfg:
      classes: ['Car', 'Pedestrian']
      pyramid_levels: [4]
      strides: [16]
      sizes: [24]
      ratios: [0.5, 1, 2.0]
      # [2 ** (i / 4.0) for i in range(16)]
      scales: [1.0, 1.189207115002721, 1.4142135623730951, 1.681792830507429, 
                2.0, 2.378414230005442, 2.8284271247461903, 3.363585661014858,
                4.0, 4.756828460010884, 5.656854249492381, 6.727171322029716,
                8.0, 9.513656920021768, 11.313708498984761, 13.454342644059432]
    
    layer_cfg:
      num_cls_output: 3
      num_reg_output: 12
      cls_feature_size: 256
      reg_feature_size: 1408
    
    loss_cfg:
      fg_iou_threshold: 0.5
      bg_iou_threshold: 0.4
      L1_regression_alpha: 10
      focal_loss_gamma: 2.0
      balance_weight: [20.0, 40]
      # [x, y, w, h, cx, cy, z, sin2a, cos2a, w, h, l]
      regression_weight: [1, 1, 1, 1, 1, 1, 12, 1, 1, 0.5, 0.5, 0.5, 1]
    
    test_cfg:
      score_thr: 0.75
      cls_agnostic: False
      nms_iou_thr: 0.4
      post_optimization: false

trainer:
  gpu: 0
  max_epochs: 80
  disp_iter: 100
  save_iter: 5
  test_iter: 10
  training_func: train_stereo_detection
  test_func: test_stereo_detection
  evaluate_func: evaluate_kitti_obj

optimizer:
  name: adam
  kwargs:
    learning_rate: 0.0001
    # weight_decay: 0
  clipped_gradient_norm: 0.1

scheduler:
  name: StepLR
  kwargs:
    learning_rate: 0.001
    step_size: 10